apiVersion: v1
kind: Pod
metadata:
  name: pg-db
  labels:
    app: pg-db
spec:
  containers:
  - name: con-pg-db
    image: postgres:13-alpine
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_PASSWORD
        value: password
      - name: PGDATA
        value: /var/lib/postgresql/data/pgdata   
    volumeMounts:
      - mountPath: /var/lib/postgresql/data
        name: pg-db
  volumes:
    - name: pg-db
#      persistentVolumeClaim:
#        claimName: pvc-pg-db
      awsElasticBlockStore:
        volumeID: vol-09eba3f49b6576e6f
        fsType: ext4
