apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pg-db
  labels:
    app: pg-db
spec:
  storageClassName: sc-ebs
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  

    
  