apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-ebs
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  iopsPerGB: "10000"
  fstype: ext4
reclaimPolicy: Retain  
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer